CRYPTO_ASSETS = [
    {
        "base_symbol": "BTC",
        "canonical_symbol": "BTCUSDT",
        "display_name": "BTC",
        "aliases": ["BTC", "BTCUSDT", "BTC-USD"],
        "market": "BINANCE",
        "currency": "USDT",
        "yahoo_fallback_symbol": "BTC-USD",
    },
    {
        "base_symbol": "ETH",
        "canonical_symbol": "ETHUSDT",
        "display_name": "ETH",
        "aliases": ["ETH", "ETHUSDT", "ETH-USD"],
        "market": "BINANCE",
        "currency": "USDT",
        "yahoo_fallback_symbol": "ETH-USD",
    },
    {
        "base_symbol": "BNB",
        "canonical_symbol": "BNBUSDT",
        "display_name": "BNB",
        "aliases": ["BNB", "BNBUSDT", "BNB-USD"],
        "market": "BINANCE",
        "currency": "USDT",
        "yahoo_fallback_symbol": "BNB-USD",
    },
    {
        "base_symbol": "SOL",
        "canonical_symbol": "SOLUSDT",
        "display_name": "SOL",
        "aliases": ["SOL", "SOLUSDT", "SOL-USD"],
        "market": "BINANCE",
        "currency": "USDT",
        "yahoo_fallback_symbol": "SOL-USD",
    },
    {
        "base_symbol": "XRP",
        "canonical_symbol": "XRPUSDT",
        "display_name": "XRP",
        "aliases": ["XRP", "XRPUSDT", "XRP-USD"],
        "market": "BINANCE",
        "currency": "USDT",
        "yahoo_fallback_symbol": None,
    },
    {
        "base_symbol": "DOGE",
        "canonical_symbol": "DOGEUSDT",
        "display_name": "DOGE",
        "aliases": ["DOGE", "DOGEUSDT", "DOGE-USD"],
        "market": "BINANCE",
        "currency": "USDT",
        "yahoo_fallback_symbol": None,
    },
]

