TW_STOCKS = [
    {
        "canonical_symbol": "2330.TW",
        "display_name": "台積電",
        "aliases": ["台積電", "TSMC", "2330", "2330.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2454.TW",
        "display_name": "聯發科",
        "aliases": ["聯發科", "MEDIATEK", "2454", "2454.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2317.TW",
        "display_name": "鴻海",
        "aliases": ["鴻海", "FOXCONN", "2317", "2317.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2382.TW",
        "display_name": "廣達",
        "aliases": ["廣達", "QUANTA", "2382", "2382.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "3231.TW",
        "display_name": "緯創",
        "aliases": ["緯創", "WISTRON", "3231", "3231.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2308.TW",
        "display_name": "台達電",
        "aliases": ["台達電", "DELTA", "2308", "2308.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "3711.TW",
        "display_name": "日月光",
        "aliases": ["日月光", "ASE", "3711", "3711.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "6669.TW",
        "display_name": "緯穎",
        "aliases": ["緯穎", "WIWYNN", "6669", "6669.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2376.TW",
        "display_name": "技嘉",
        "aliases": ["技嘉", "GIGABYTE", "2376", "2376.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2357.TW",
        "display_name": "華碩",
        "aliases": ["華碩", "ASUS", "2357", "2357.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2383.TW",
        "display_name": "台光電",
        "aliases": ["台光電", "EMC", "2383", "2383.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2882.TW",
        "display_name": "國泰金",
        "aliases": ["國泰金", "CATHAY", "2882", "2882.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2881.TW",
        "display_name": "富邦金",
        "aliases": ["富邦金", "FUBON", "2881", "2881.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2891.TW",
        "display_name": "中信金",
        "aliases": ["中信金", "CTBC", "2891", "2891.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2884.TW",
        "display_name": "玉山金",
        "aliases": ["玉山金", "ESUN", "2884", "2884.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2603.TW",
        "display_name": "長榮",
        "aliases": ["長榮", "EVERGREEN", "2603", "2603.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2609.TW",
        "display_name": "陽明",
        "aliases": ["陽明", "YANG MING", "2609", "2609.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2615.TW",
        "display_name": "萬海",
        "aliases": ["萬海", "WAN HAI", "2615", "2615.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "2412.TW",
        "display_name": "中華電",
        "aliases": ["中華電", "CHT", "2412", "2412.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "3045.TW",
        "display_name": "台灣大",
        "aliases": ["台灣大", "TAIWAN MOBILE", "3045", "3045.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
    {
        "canonical_symbol": "4904.TW",
        "display_name": "遠傳",
        "aliases": ["遠傳", "FAREASTONE", "4904", "4904.TW"],
        "market": "TWSE",
        "currency": "TWD",
    },
]

